#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Python startup file, executed when entering the interactive mode.
# This file is suggested to be put under ~/ and renamed as .pythonstartup.
# An environment variable 'PYTHONSTARTUP' should be defined as:
#
# export PYTHONSTARTUP=".pythonstartup"
#
# Put the above line in ~/.bashrc or ~/.bash_profile.
#
# Author : Liu Sibo
# Email  : liusibojs@dangdang.com
# Date   : 2019-01-10

import sys
import readline
import rlcompleter
import atexit
import os

# tab completion
readline.parse_and_bind('tab: complete')

# history file
histfile = os.path.join(os.environ['HOME'], '.pythonhistory')

try:
    readline.read_history_file(histfile)
except IOError:
    pass

atexit.register(readline.write_history_file, histfile)
